# Generated by Django 6.0 on 2025-12-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('fuel_dispensed', models.FloatField(help_text='Liters dispensed (from Pump/CCTV)')),
                ('bill_amount', models.FloatField(help_text='Amount claimed by customer')),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('is_fraud', models.BooleanField(default=False)),
                ('fraud_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('fraud_type', models.CharField(blank=True, choices=[('SCREENSHOT_TAMPERED', 'Fake/Edited Screenshot'), ('AMOUNT_MISMATCH', 'Fuel vs Bill Mismatch'), ('DUPLICATE', 'Duplicate Transaction'), ('ANOMALY', 'Suspicious Pattern')], max_length=50, null=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
