# Generated by Django 6.0 on 2025-12-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fraudalert',
            name='confidence_score',
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='pump_image',
            field=models.ImageField(blank=True, help_text='Upload photo of Pump Meter (CCTV Sim)', null=True, upload_to='pump_cctv/'),
        ),
        migrations.AlterField(
            model_name='fraudalert',
            name='fraud_type',
            field=models.CharField(blank=True, choices=[('SCREENSHOT_TAMPERED', 'Fake/Edited Screenshot'), ('AMOUNT_MISMATCH', 'Fuel vs Bill Mismatch'), ('DUPLICATE', 'Duplicate Transaction'), ('ANOMALY', 'Suspicious Pattern'), ('PUMP_MISMATCH', 'CCTV vs Bill Mismatch')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fraudalert',
            name='fuel_dispensed',
            field=models.FloatField(help_text='Liters claimed by customer/staff'),
        ),
    ]
