# Generated by Django 6.0 on 2025-12-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_fraudalert_confidence_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudalert',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='ela_evidence',
            field=models.ImageField(blank=True, help_text='Forensic Analysis Image', null=True, upload_to='ela_evidence/'),
        ),
        migrations.AlterField(
            model_name='fraudalert',
            name='fuel_dispensed',
            field=models.FloatField(help_text='Liters dispensed (from Pump/CCTV)'),
        ),
    ]
